//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisitorInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitorInformation
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Company { get; set; }
        public string Visiting { get; set; }
        public string IDType { get; set; }
        public string IDNumber { get; set; }
        public string VehicleNumber { get; set; }
        public string ContactNumber { get; set; }
        public string PurposeOfVisit { get; set; }
        public string Status { get; set; }
        public System.DateTime CheckInTime { get; set; }
        public System.DateTime CheckOutTime { get; set; }
    }
}
